[tools]
cargo-binstall = "1.12.3"
"cargo:aoc-cli" = "0.12.0"
uv = "latest"

[tasks."check"]
depends = ["check:*"]

[tasks."check:test"]
run = "uv run pytest"
wait_for = ["fix:*"]

[tasks."check:type"]
run = "uv run mypy ."
wait_for = ["fix:*"]

[tasks."check:fmt"]
run = "uv run ruff format --check ."
wait_for = ["fix:*"]

[tasks."check:lint"]
run = "uv run ruff check ."
wait_for = ["fix:*"]

[tasks."fix"]
depends = ["fix:*"]

[tasks."fix:fmt"]
run = "uv run ruff format ."
wait_for = ["fix:lint"]

[tasks."fix:lint"]
run = "uv run ruff check --fix ."
